### ISSUE TITLE
WooCommerce Default country will save, But does not show correctly

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [MahdiY/Persian-woocommerce-shipping#1]
**Describe the bug**
In the Configuration page of WooCommerce, When select a default country and press save button, the info will save in DB correctly, But after reload the page, when the select box will load, the default item selected on select box is not correct item.

**To Reproduce**
1. Go to 'WooCommerce Configuration'
2. Click on 'Country/Province'
3. Select any country
4. Save
5. After reload look at Country item.

**Expected behavior**
Should select correct country as default selected item in select box.

**More Information**
I have installed the latest version few minutes ago and reproduced this problem in new version.
I have checked only this plugin will generate this problem to WooCommerce, When I disable this plugin the problem will gone away.

**Comment by AmirHosseinKarimi** [comment]
Hi, I was checked the latest version of this plugin (2.1.2) with following change log message: Fix: State & city field style
If this update should fix this problem, I should say I tested it and this won't do it.

**Comment by MahdiY** [comment]
Hi Amir,

Bug fixed, Thank you for reporting.
