### ISSUE TITLE
Fire card updated event on changing delivery method

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [MahdiY/Persian-woocommerce-shipping#3]
Hi, When user changing delivery method in card page, looks like plugin will fire an event like cart is updated, and theme will prompt about Cart was updated successfully.
I have **Orchid Store** theme and think its not theme problem.
I have tested Store Front theme, But this theme has not this problem.
Can you help me to fix this problem if its from theme?

**Comment by MahdiY** [comment]
Hi,
Unfortunately, Woocommerce does not offer flexible coding in the shipping section on the cart page. I suggest you disable the shipping section on the cart page.
