### ISSUE TITLE
Cannot send to Tapin when `Force shipping to the customer billing address` is enabled

### ISSUE THREAD

**Issue by geminorum** [MahdiY/Persian-woocommerce-shipping#4]
Hi,

Upon disabling shipping address (i.e. `wc_ship_to_billing_address_only()`), I get in-valid notices.

![photo_2020-10-07_10-51-35](https://user-images.githubusercontent.com/150718/95336606-bb59d580-08bd-11eb-80f3-ed8e416429a8.jpg)

Note that it will be working if I manually fill the shipping address/name fields.

**Comment by MahdiY** [comment]
Hi 
First of all, I apologize for the delay in responding. Are you using a plugin to edit checkout fields?

Please send me a screenshot of the following two paths. 
1. Full screenshot of the view page of an order where this error occurs. 
2. WooCommerce / Shipping / Shipping Options

Which version of the WordPress and following plugins/themes do you use?

1. Woocommerce
2. Persian Woocommerce
3. Persian Woocommerce Shipping

**Comment by MahdiY** [comment]
@geminorum Thank you for bug reporting. This bug was fixed in version 3.0.0.
